M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu20.04.1} date Mon 07 Oct 2024 06:02:05 PM CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-10-07T18:02:05+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X133.9Y-77.158
T1
X133.9Y-84.208G85X133.9Y-84.508
G05
M30
